import type { Testimonial } from '@/components/blocks/TestimonialCard'

export const testimonials: Testimonial[] = [
  {
    id: '1',
    quote: 'You are our secret weapon. Keep your diary clear, please!',
    author: 'Gary Lubner',
    title: 'CEO',
    company: 'Belron International',
    image: '/images/testimonials/gary-lubner.png',
    featured: true,
  },
  {
    id: '2',
    quote: 'We hired Rob as our Copy Chief for CA Labs!',
    author: 'Stefan Georgi',
    title: 'Founder',
    company: 'Copy Accelerator',
    image: '/images/testimonials/stefan-georgi.jpeg',
    featured: true,
  },
  {
    id: '3',
    quote: 'A big shoutout to Rob Palmer who stepped up and knocked it out of the park.',
    author: 'Justin Goff',
    title: 'Direct Marketer',
    company: '',
    image: '/images/testimonials/justin-goff.jpeg',
    featured: true,
  },
  {
    id: '4',
    quote: 'Rob is a killer copywriter. We\'re getting a 300% Return on Ad Spend...',
    author: 'Ben Palmer',
    title: 'ClickBank Platinum Vendor',
    company: '',
    image: '/images/testimonials/ben-palmer.png',
    featured: true,
  },
  {
    id: '5',
    quote: 'The funnel you wrote is doing great. Sales page converting at 8% on cold traffic.',
    author: 'Conor Reynolds',
    title: 'Online Marketer',
    company: '',
    image: '/images/testimonials/conor-reynolds.png',
    featured: true,
  },
  {
    id: '6',
    quote: 'Rob is probably the most methodical copywriter I\'ve seen. This impresses me.',
    author: 'Mark Shay',
    title: 'Supplement Marketer',
    company: '',
    image: '/images/testimonials/mark-shay.png',
    featured: true,
  },
  {
    id: '7',
    quote: 'Your quality of writing is off the charts better.',
    author: 'John Immel',
    title: 'Founder',
    company: 'Zero to One',
    image: '/images/testimonials/john-immel.jpg',
  },
  {
    id: '8',
    quote: 'All I can say is absolutely brilliant, Rob! I can\'t improve on it.',
    author: 'Zane Myers',
    title: 'Entrepreneur',
    company: '',
    image: '/images/testimonials/zane-myers.jpeg',
  },
  {
    id: '9',
    quote: 'Everything is on point and on brief! You knocked it out of the park with those!',
    author: 'Devon Brown',
    title: 'Founder',
    company: 'JTSSOI',
    image: '/images/testimonials/devon-brown.jpeg',
  },
  {
    id: '10',
    quote: 'Getting copy back from Rob is like Moses receiving the Ten Commandments from God.',
    author: 'Keith Mueller',
    title: 'Entrepreneur',
    company: '',
    image: '/images/testimonials/keith-mueller.png',
  },
  {
    id: '11',
    quote: 'Rob is amazing. He got right to the crux of my copy problem.',
    author: 'Andrew Stotz',
    title: 'CEO',
    company: 'Stotz Financial Research',
    image: '/images/testimonials/andrew-stotz.jpeg',
  },
  {
    id: '12',
    quote: 'This script looks awesome, thank you so much! I can\'t believe how fast you are!',
    author: 'Jenn Le Compte',
    title: 'Super Affiliate',
    company: '',
    image: '/images/testimonials/jenn-lecompte.png',
  },
  {
    id: '13',
    quote: 'Great work that exceeded expectations. Amazing copy and top-notch service.',
    author: 'Amber Saunders',
    title: 'Attorney',
    company: 'The Saunders Firm',
    image: '/images/testimonials/amber-saunders.jpeg',
  },
  {
    id: '14',
    quote: 'Your copy is outstanding. Pure gold...this offer will surely be top thanks to you!',
    author: 'Cosmin Panait',
    title: 'Founder',
    company: 'Media Map Marketing',
    image: '/images/testimonials/cosmin-panait.jpg',
  },
  {
    id: '15',
    quote: 'One of your ads has just taken the lead. High-converting campaign!',
    author: 'Marc David Lindsay',
    title: 'Direct Response Marketer',
    company: '',
    image: '/images/testimonials/marc-lindsay.jpg',
  },
  {
    id: '16',
    quote: 'Woah, this script is awesome! The squeeze page copy is crushing the old one.',
    author: 'Sam P.',
    title: 'Lead-Gen Specialist',
    company: '',
    image: '/images/testimonials/sam-p.png',
  },
  {
    id: '17',
    quote: 'That\'s solid copy. I have a feeling this is going to be a winner. Great job!',
    author: 'Ryan Kowalski',
    title: 'Marketer',
    company: 'Konscious Keto',
    image: '/images/testimonials/ryan-kowalski.png',
  },
  {
    id: '18',
    quote: 'Rob, high five!! You da Man! Great to get that bump in conversions!',
    author: 'Caleb O\'Dowd',
    title: 'Direct Response Marketer',
    company: '',
    image: '/images/testimonials/caleb-odowd.jpg',
  },
  {
    id: '19',
    quote: 'My team loved the copy you generated.',
    author: 'Darian James',
    title: 'Founder',
    company: 'Dash Activate',
    image: '/images/testimonials/darian-james.jpeg',
  },
  {
    id: '20',
    quote: 'Overall, I really like your writing, and your copy really stands out.',
    author: 'Christian Green',
    title: 'Marketer',
    company: 'ClickBank',
  },
  {
    id: '21',
    quote: 'Great. The Video Sales Letter script looks good. You nailed it!',
    author: 'Stephen Esketzis',
    title: 'Entrepreneur',
    company: '',
    image: '/images/testimonials/stephen-esketzis.png',
  },
  {
    id: '22',
    quote: 'Rob, you are awesome. I love it. And Holy Moly, you are super quick!',
    author: 'Kristy Plucker',
    title: 'CEO',
    company: 'Chatterkick',
    image: '/images/testimonials/kristy-plucker.jpeg',
  },
  {
    id: '23',
    quote: 'I have to say that they were positively impressed with your work.',
    author: 'William Vanhout',
    title: 'Founder',
    company: 'Connectio',
    image: '/images/testimonials/william-vanhout.jpeg',
  },
  {
    id: '24',
    quote: 'This is exactly what I wanted. Awesome work, Rob.',
    author: 'Steven Piper',
    title: 'Founder',
    company: 'LeadHub',
    image: '/images/testimonials/steven-piper.jpeg',
  },
  {
    id: '25',
    quote: 'Rob, I have read through the VSL script. No issues. Looks great. Well done!',
    author: 'Tom Barnes',
    title: 'Entrepreneur',
    company: '',
    image: '/images/testimonials/tom-barnes.png',
  },
  {
    id: '26',
    quote: 'Just reviewed the script...great work! Edits are minimal.',
    author: 'Francis Fanzilli',
    title: 'Partner',
    company: 'Red Oak Capital',
    image: '/images/testimonials/francis-fanzilli.png',
  },
  {
    id: '27',
    quote: 'Rob\'s work is of excellent quality. His writing is very clean.',
    author: 'Kim Benkhe',
    title: 'Editor',
    company: 'Black & White Zebra',
    image: '/images/testimonials/kim-benkhe.png',
  },
  {
    id: '28',
    quote: 'Wow, so fast! It looks great...I love it!',
    author: 'Sabrena Carey',
    title: 'Affiliate Marketer',
    company: '',
    image: '/images/testimonials/sabrena-carey.png',
  },
  {
    id: '29',
    quote: 'Looks fantastic! Great work overall...I\'m sure this will bring in lots of new business!',
    author: 'Wendell Pfeiffer',
    title: 'Fitness Coach',
    company: '',
    image: '/images/testimonials/wendell-pfeiffer.jpg',
  },
  {
    id: '30',
    quote: 'Great work on this...overall, really well done. Fantastic work, Rob!',
    author: 'Ryan Hood',
    title: 'Direct Response Marketer',
    company: '',
    image: '/images/testimonials/ryan-hood.png',
  },
  {
    id: '31',
    quote: 'I really like the copy. Looks very good.',
    author: 'Bob Diamond',
    title: 'Founder',
    company: 'Overages Blueprint',
    image: '/images/testimonials/bob-diamond.jpg',
  },
  {
    id: '32',
    quote: 'Really good copy. More projects coming your way soon!',
    author: 'Doug Beney',
    title: 'Founder',
    company: 'Ecom Authority',
    image: '/images/testimonials/doug-beney.jpg',
  },
  {
    id: '33',
    quote: 'This is great, Rob. Awesome job! You are a pro.',
    author: 'Behdad Jamshidi',
    title: 'CEO',
    company: 'CJAM Marketing',
    image: '/images/testimonials/behdad-jamshidi.jpeg',
  },
  {
    id: '34',
    quote: 'Once again, this looks great, Rob. We will circle back soon.',
    author: 'Byron Walker',
    title: 'Marketer',
    company: 'Survival Frog',
    image: '/images/testimonials/byron-walker.jpeg',
  },
  {
    id: '35',
    quote: 'Thanks again for your hard work. Totally appreciated.',
    author: 'Frank Sanya',
    title: 'CEO',
    company: 'Market Leaders Realty',
    image: '/images/testimonials/frank-sanya.jpeg',
  },
  {
    id: '36',
    quote: 'The VSL script looks great overall and I like it. I think we\'re good.',
    author: 'Francis Fanzilli',
    title: 'Partner',
    company: 'Red Oak Capital',
    image: '/images/testimonials/francis-fanzilli.png',
  },
  {
    id: '37',
    quote: 'OMG, Rob…you are the best-ever, ALL TIME! Thank you so much!!!!!!',
    author: 'Christopher Gyorgy',
    title: '',
    company: '',
    image: '',
  },
  {
    id: '38',
    quote: 'As usual, you demonstrate great professionalism. We know that experienced copywriters typically have significant skills, but we\'re truly impressed by your approach. We are really excited and fully satisfied with the work done: excellent result!',
    author: 'Giacomo Fusari',
    title: 'CEO',
    company: 'Arte Riconquista',
    image: '',
  },
]

export const featuredTestimonials = testimonials.filter((t) => t.featured)
